config:
  deprecated: true 
  
  extensions:
  - $spack/../spack-mpd
  
  mpd_user_dir: $spack/../spack-repos/mpd

  install_tree: 
    #padded_length:255
    projections:
      all: "{name}/{version}/{architecture}-{compiler.name}-{compiler.version}-{hash}"
    root: $spack/../../..
    
  template_dirs:
  - $spack/share/spack/templates
  
  license_dir: $spack/etc/spack/licenses

  build_stage:
  - $tempdir/$user/spack-stage
  - $user_cache_path/stage
  
  test_stage: $user_cache_path/test
  
  source_cache: $spack/var/spack/cache
  
  misc_cache: $user_cache_path/cache
  
  connect_timeout: 10
  
  verify_ssl: true
  
  ssl_certs: $SSL_CERT_FILE
  
  suppress_gpg_warnings: false
  
  checksum: true
  
  dirty: false
  
  build_language: C
  
  url_fetch_method: urllib
  
  ccache: false
  
  db_lock_timeout: 60
 
  package_lock_timeout: null
  
  shared_linking:
    type: rpath
    bind: false
    missing_library_policy: ignore


  allow_sgid: true
  
  install_status: true
  
  binary_index_ttl: 600
 
  flags:
    keep_werror: none

  aliases:
    concretise: concretize
    containerise: containerize
    rm: remove
  
  debug: false
  
  build_jobs: 16
